version: "2"
services:

  server:
    build: mongo-with-automation
    depends_on:
      - opsmanager
    links:
      - opsmanager
    environment:
      TERM: xterm
    expose:
      - 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro

  outward_server:
    build: mongo-with-automation
    depends_on:
      - opsmanager
    links:
      - opsmanager
    environment:
      TERM: xterm
    expose:
      - 27017
    ports:
      - 27000-28000:27000-28000
    volumes:
      - /etc/localtime:/etc/localtime:ro

  opsmanager_mongo:
    image: mongo:3.4
    command: mongod --noprealloc --smallfiles --oplogSize 16 --noauth --rest
    environment:
      TERM: xterm
    expose:
      - 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - opsmanager_mongovol:/data/db

  opsmanager:
    build: ops-manager/
    depends_on:
      - opsmanager_mongo
    links:
      - opsmanager_mongo
      - mailcatcher
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
     - ./share/mongodb-mms:/etc/mongodb-mms
     - ./share:/tmp/share

  mailcatcher:
    image: schickling/mailcatcher
    ports: 
      - 1025:1025
      - 1080:1080

volumes:
  opsmanager_mongovol:
