#!/bin/bash

for (( rs = 1; rs < 3; rs++ )); do
  echo "Intializing replica ${rs} set"
  docker-compose exec app_mongos1 bash -c "/tmp/share/wait-for-it.sh app_rs${rs}n1:27018;/tmp/share/wait-for-it.sh app_rs${rs}n2:27018;/tmp/share/wait-for-it.sh app_rs${rs}n3:27018;"
  replicate="rs.initiate(); sleep(1000); cfg = rs.conf(); cfg.members[0].host = \"app_rs${rs}n1:27018\"; sleep(1000);rs.reconfig(cfg); rs.add(\"app_rs${rs}n2:27018\"); rs.addArb(\"app_rs${rs}n3:27018\"); rs.status();"
  docker-compose exec app_rs${rs}n1 bash -c "echo '${replicate}' | mongo --port 27018"
done

echo "Intializing replica set for mongoconfig"
replicate="rs.initiate(); sleep(1000); cfg = rs.conf(); cfg.members[0].host = \"app_cfg1:27019\"; rs.reconfig(cfg); rs.add(\"app_cfg2:27019\"); rs.add(\"app_cfg3:27019\"); rs.status();"
docker-compose exec app_cfg1 bash -c "echo '${replicate}' | mongo --port 27019"


docker-compose exec app_mongos1 bash -c "/tmp/share/wait-for-it.sh app_cfg1:27019;/tmp/share/wait-for-it.sh app_cfg2:27019;/tmp/share/wait-for-it.sh app_cfg1:27019;"

# Add better mechanisum to wait for app_mongos connectivity to be
# established by tailing docker log for connection readiness
echo "Intializing shards through router"
docker-compose exec app_mongos1 bash -c "/tmp/share/wait-for-it.sh -t 60 app_mongos1:27017;/tmp/share/wait-for-it.sh app_mongos2:27017"
docker-compose exec app_mongos1 bash -c "echo \"sh.addShard('app_rs1/app_rs1n1:27018,app_rs1n2:27018'); sh.addShard('app_rs2/app_rs2n1:27018,app_rs2n2:27018');sh.status()\" | mongo "
